---
title: "FDC ABCT 2023 EFA"
output: html_document
date: '2023-01-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("GPArotation")
```


```{r}
#importing libraries
library(psych)
library(corrplot)
library("psych")
library(ggplot2)
library(GPArotation)
```


```{r}
#bringing in the data

fdc = read.csv("C:/Users/Luis/Dropbox/independent stuff/Family Diet Culture/ABCT2023/EFA dataset.csv")
fdc

```

```{r}
describe(fdc)
```
```{r}
dim(fdc)
```
```{r}
dat = fdc[ ,-44]
head(dat)
```

```{r}
dat = na.omit(dat)
colnames(dat)[1]="fdcq_1"
dat
names(dat) = sub('^fdcq_', '', names(dat))
dat
```


```{r}
datamatrix = cor(dat[,c(-13)])
corrplot(datamatrix, method='circle', addCoef.col = 1, number.cex = 0.4, res=500)
```
```{r}
corrplot(datamatrix, method='color', addCoef.col = 1, number.cex = 0.4, res=500)
```
```{r}
x = dat[,-c(13)]
y = dat[,13]
```

```{r}
x
```
```{r}
y
```

```{r}
KMO(r=cor(x))
```

```{r}
cortest.bartlett(x)

```
```{r}
library(ggplot2)
dietculture = fa(dat,nfactors=ncol(x), rotate="none")
n_factors = length(dietculture$e.values)
scree = data.frame(Factor_n = as.factor(1:n_factors), Eigenvalue = dietculture$e.values)
ggplot(scree, aes(x=Factor_n, y=Eigenvalue, group=1))+ geom_point() + geom_line() + xlab("Number of factors") + ylab("Initial eigenvalue") + labs(title = "Scree Plot", subtitle = "(Based on the reduced correlation matrix)") 
```
```{r}
parallel = fa.parallel(x)
```

```{r}
fa.none = fa(r=x, 
             nfactors=4, 
             # covar = FALSE, 
             SMC = TRUE, 
             fm="pa", 
             max.iter=100)
fa.none

```

```{r}
fa.none
```

```{r}
fa.none1 = fa(r=x, 
             nfactors=3, 
             # covar = FALSE, 
             SMC = TRUE, 
             fm="pa", 
             max.iter=100)
fa.none1
```

